# Generated by Django 3.0.2 on 2020-04-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, unique=True, verbose_name='Course Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('subject_number', models.CharField(max_length=10, verbose_name='Subject code')),
                ('nature', models.CharField(max_length=10, verbose_name='Subject Nature')),
                ('description', models.TextField(verbose_name='Short Description')),
                ('syllabus', models.URLField(verbose_name='Google Drive link of Syllabus PDF')),
                ('semester', models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'eighth')], max_length=10, verbose_name='Semester')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'unique_together': {('subject_number', 'course')},
            },
        ),
        migrations.CreateModel(
            name='PractiseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link of PDF/ Docs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='OldQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link of PDF/ Docs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link of PDF/ Docs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='LabManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link of PDF/ Docs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link of PDF/ Docs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
    ]
