# Generated by Django 3.0.2 on 2020-04-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='nature',
            field=models.CharField(choices=[('Theory + Practical', 'Theory + Practical'), ('Theory', 'Theory'), ('Practical', 'Practical')], max_length=50, verbose_name='Subject Nature'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'eighth')], max_length=10, verbose_name='Semester'),
        ),
    ]
