# Generated by Django 3.0.2 on 2020-04-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200417_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit_hours',
            field=models.CharField(default=3, max_length=3, verbose_name='Credit Hours'),
        ),
    ]
